# DIMENSIONS OF THE MAZE
MAZE_WIDTH = 15
MAZE_HEIGHT = 15

# DIMENSIONS OF EACH ELEMENT'S PICTURE IN THE MAZE
PIC_WIDTH = 40
PIC_HEIGHT = 40

# WITCH ELEMENT IT IS
AETHER = 'A'
BEGIN = 'B'
EXIT = 'E'
FLOOR = '.'
GUARDIAN = 'G'
MAC_GYVER = 'M'
NEEDLE = 'N'
TUBE = 'T'
WALL = 'W'

# HOW MANY PIECES TO COMPLETE SYRINGE
NUMBER_TO_COLLECT = 3

# Status at the end of game
FREE_FLOOR = 0
NO_SYRINGE = 1
FILLED_SYRINGE = 2
DONT_MOVE = 3
